
# Use ubuntu trusty (14.04) with ros indigo on travis

dist: trusty
sudo: required
language:
  - generic
cache:
  - apt

env:
  global:
    - ROS_DISTRO=indigo
    - CI_SOURCE_PATH=$(pwd)

before_install:
  - lsb_release -a
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sudo apt-get update -qq
  - sudo apt-get install ros-$ROS_DISTRO-ros-base
  - sudo apt-get install ros-$ROS_DISTRO-move-base ros-$ROS_DISTRO-ompl
  - sudo apt-get install python-catkin-pkg python-empy python-rospkg
  - pip install catkin_pkg
  - pip install rospkg
  - sudo rosdep init
  - rosdep update
install:
  # make a workspace and checkout the right repos:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ..
  - catkin_make
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH . # link repo under test.
before_script:
  - source ~/catkin_ws/devel/setup.bash
  - cd ~/catkin_ws/src
script:
  - cd ~/catkin_ws
  - catkin_make
